codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project: true
    patch: yes
    changes: no
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
ignore:
  - "src/main/java/org/odessajavaclub/config"
  - "src/main/java/org/odessajavaclub/user/config"
  - "src/main/java/org/odessajavaclub/user/bootstrap"
  - "src/main/java/org/odessajavaclub/user/adapter/in/rest/model"
  - "src/main/java/org/odessajavaclub/user/adapter/in/rest/mapper"
  - "src/main/java/org/odessajavaclub/user/adapter/in/springevents/model"
  - "src/main/java/org/odessajavaclub/user/adapter/in/springevents/mapper"
  - "src/main/java/org/odessajavaclub/user/adapter/out/jpa/model"
  - "src/main/java/org/odessajavaclub/user/adapter/out/jpa/mapper"